pkg/executor/workflow.go
pkg/executor/workflow_test.go

Fix: fix backoff time bug when step execution exceeds default backoff time

---

api/v1alpha1/event.go
api/v1alpha1/types.go
controllers/workflow_test.go
controllers/workflowrun_controller.go
pkg/executor/workflow.go
pkg/executor/workflow_test.go

Add failed state in workflow to separate failed and terminated
I have:

Feat: add failed state in workflow

---

makefiles/e2e.mk
pkg/stdlib/packages.go
pkg/stdlib/packages_test.go

Fix: unify stdlib for workflow and kubevela

---

charts/vela-workflow/README.md
pkg/cue/model/value/value.go
pkg/cue/model/value/value_test.go
pkg/tasks/custom/task.go
pkg/tasks/custom/task_test.go
pkg/types/types.go

Fix: fix fill array with array in inputs
I have:
cc @chivalryq

Fix: fix fill array with array in inputs

---

charts/vela-workflow/README.md
charts/vela-workflow/templates/workflow-controller.yaml
charts/vela-workflow/values.yaml
cmd/main.go

Feat: add user agent in config

---

pkg/cue/model/sets/operation.go
pkg/cue/model/sets/utils.go
pkg/cue/model/sets/walk.go
pkg/cue/model/value/value.go
pkg/cue/model/value/value_test.go
pkg/cue/utils.go
pkg/cue/utils_test.go
pkg/providers/kube/handle.go
pkg/providers/kube/handle_test.go

Feat: add substitute unstructured object

---

pkg/tasks/custom/task.go
pkg/tasks/custom/task_test.go

In the following example, if `response.data` is a struct that contains multiple fields, the if statement will parse incorrectly.
this PR fix this bug.
```
response: data: {
success: true
code: 200
}
```
```
- name: test-step
subSteps:
- name: test-subStep-1
outputs:
- name: subStep-1-result
valueFrom: response.data
type: webhook
- if:  inputs["subStep-1-result"].success == true
inputs:
- from: subStep-1-result
name: test-subStep-2
type: webhook
```
I have:

Fix: input error stores structure type data

---

controllers/workflow_test.go
controllers/workflowrun_controller.go
pkg/context/context.go
pkg/context/context_test.go
pkg/executor/workflow.go
pkg/executor/workflow_test.go
pkg/features/controller_features.go
pkg/hooks/data_passing_test.go
pkg/tasks/custom/task_test.go
pkg/types/types.go

Feat: add feature gates for patch step status at once

---

README.md
examples/initialize-env.md
examples/multiple-apps.md
examples/request-and-notify.md
examples/run-with-template.md
examples/workflow-run/apply-terraform-resource.yaml

Feat: add apply terraform example yaml

---

pkg/context/context.go
pkg/context/context_test.go
pkg/executor/workflow.go
pkg/hooks/data_passing_test.go
pkg/tasks/custom/task_test.go

Fix: set gvk for created cm to fix patch

---

api/v1alpha1/types.go
charts/vela-workflow/crds/core.oam.dev_workflowruns.yaml
charts/vela-workflow/crds/core.oam.dev_workflows.yaml
charts/vela-workflow/templates/admission-webhooks/certmanager.yaml
charts/vela-workflow/templates/admission-webhooks/job-patch/clusterrole.yaml
charts/vela-workflow/templates/admission-webhooks/job-patch/clusterrolebinding.yaml
charts/vela-workflow/templates/admission-webhooks/job-patch/job-createSecret.yaml
charts/vela-workflow/templates/admission-webhooks/job-patch/job-patchWebhook.yaml
charts/vela-workflow/templates/admission-webhooks/job-patch/role.yaml
charts/vela-workflow/templates/admission-webhooks/job-patch/rolebinding.yaml
charts/vela-workflow/templates/admission-webhooks/job-patch/serviceaccount.yaml
charts/vela-workflow/templates/admission-webhooks/mutatingWebhookConfiguration.yaml
charts/vela-workflow/templates/admission-webhooks/validatingWebhookConfiguration.yaml
charts/vela-workflow/templates/admission-webhooks/webhookService.yaml
charts/vela-workflow/values.yaml
cmd/main.go
controllers/suite_test.go
controllers/workflowrun_controller.go
go.mod
pkg/webhook/register.go
pkg/webhook/v1alpha1/workflowrun/mutating_handler.go
pkg/webhook/v1alpha1/workflowrun/mutating_handler_test.go
pkg/webhook/v1alpha1/workflowrun/suite_test.go
pkg/webhook/v1alpha1/workflowrun/validating_handler.go
pkg/webhook/v1alpha1/workflowrun/validating_handler_test.go
pkg/webhook/v1alpha1/workflowrun/validation.go

Feat: add webhook and auto generate name for steps

---

cmd/main.go
controllers/backup_controller.go
controllers/workflowrun_controller.go
pkg/backup/interface.go
pkg/backup/interface_test.go
pkg/backup/sls/producer.go
pkg/utils/operation.go
pkg/utils/operation_test.go

Feat: add retry failed step operation

---

controllers/suite_test.go
pkg/cue/suit_test.go
pkg/executor/suit_test.go
pkg/generator/suit_test.go
pkg/providers/config/config_test.go
pkg/providers/kube/handle_test.go
pkg/webhook/v1alpha1/workflowrun/suite_test.go

Signed-off-by: Yin Da <yd219913@alibaba-inc.com>
Remove NewLineReporter since controller-runtime new version remove it.
Reference: https://github.com/kubernetes/kubernetes/pull/110319
I have:

Chore: refactor test

---

controllers/workflow_test.go
pkg/executor/workflow.go

Fix: fix suspend bug in dag that caused by patch step status

---

controllers/workflowrun_controller.go

Fix: add cache handle if the patch is failed in end reconcile

---

cmd/main.go
controllers/backup_controller.go

Feat: add controller version in backup controller

---

README.md
charts/vela-workflow/templates/definitions/apply-app.yaml
charts/vela-workflow/templates/definitions/apply-deployment.yaml
charts/vela-workflow/templates/definitions/vela-cli.yaml

Fix: upgrade definitions in charts

---

pkg/executor/workflow.go

Fix: fix panic when workflow is skipped

---

api/v1alpha1/types.go
charts/vela-workflow/crds/core.oam.dev_workflowruns.yaml
charts/vela-workflow/crds/core.oam.dev_workflows.yaml

Signed-off-by: Qiaozp <qiaozhongpei.qzp@alibaba-inc.com>
Export `inputItem` and `outputItem` for iterating the StepInputs/Outputs array.
Fixes #
I have:

Chore: export inputItem and outputItem

---

charts/vela-workflow/templates/workflow-controller.yaml
makefiles/e2e.mk
pkg/cue/model/sets/operation.go
pkg/providers/kube/handle_test.go
pkg/utils/operation.go
pkg/utils/operation_test.go

support resume a specific suspend step in workflow
I have:

Feat: support resume a specific suspend step in workflow

---

pkg/providers/kube/handle.go
pkg/providers/kube/handle_test.go
pkg/stdlib/actions/v1/op.cue
pkg/stdlib/actions/v1/pkgs/kube.cue

remove patch in apply to make it standalone action
I have:

Fix: remove patch in apply to make it standalone action

---

controllers/testdata/multi-suspend.yaml
controllers/workflow_test.go
pkg/cue/model/value/value.go
pkg/mock/mock.go
pkg/providers/workspace/workspace.go
pkg/providers/workspace/workspace_test.go
pkg/stdlib/actions/v1/op.cue
pkg/tasks/custom/task.go
pkg/types/types.go
pkg/utils/operation.go
pkg/utils/operation_test.go

Feat: support multi suspend in definition and fix resume

---

pkg/providers/workspace/workspace.go
pkg/providers/workspace/workspace_test.go
pkg/stdlib/actions/v1/op.cue

Fix: fix auto resume in suspend

---

charts/vela-workflow/README.md
charts/vela-workflow/templates/workflow-controller.yaml
charts/vela-workflow/values.yaml
cmd/main.go
go.mod
go.sum
pkg/utils/recycle.go
pkg/utils/recycle_test.go

Add recycle grouped workflow run with cron.
The recycle function will be executed at 0 am every day. By default, if a group of workflows have the same label like `pipeline.oam.dev/name` , and all of them had been completed for a month, only the latest one is kept, and the others will be recycled.
I have:

Feat: add recycle grouped workflow run with cron

---

controllers/workflow_test.go
pkg/executor/workflow.go

Fix: fix step depends on skip

---

go.sum
pkg/generator/generator.go
pkg/providers/metrics/prom_check.go
pkg/providers/metrics/prom_check_test.go
pkg/stdlib/actions/v1/op.cue
pkg/stdlib/actions/v1/pkgs/metrics.cue

prometheus check steps provider.
Fixes #
I have:

Feat: prometheus check steps provider 

---

api/v1alpha1/types.go
charts/vela-workflow/crds/core.oam.dev_workflowruns.yaml
charts/vela-workflow/crds/core.oam.dev_workflows.yaml
controllers/workflow_test.go
go.mod
pkg/generator/generator.go

Feat: add mode in steps for step group
I have:

Feat: add mode in steps for step group

---

pkg/tasks/builtin/step_group.go

Fix: fix the step group status if there's a suspending sub step

---

controllers/workflow_test.go
pkg/utils/operation.go

Fix: fix terminate suspending steps
I have:

Fix: fix terminate suspending steps

---

pkg/stdlib/actions/v1/pkgs/task.cue

Fixes #
I have:
Have run task in my local cluster with private registry.

Feat: add image pull secret in task step

---

.github/workflows/chart.yaml
.github/workflows/e2e.yaml

Closes #180 
Update workflows to use environment file instead of deprecated `set-output` command. 
For more information, see: [https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/](https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/)
I found the workflow files that use `set-output` command through the following command:
```bash
$ find . -name '*.yml' -o -name '*.yaml' | xargs egrep '\bset-output\b'
```
**AS-IS**
```yaml
echo ::set-output name=TAG::latest
```
**TO-BE**
```yaml
echo "TAG=latest" >> $GITHUB_OUTPUT
```
I have:
None
None

Feat: replace deprecated command with environment file

---

charts/vela-workflow/templates/workflow-controller.yaml
charts/vela-workflow/values.yaml
cmd/main.go
controllers/testdata/multi-suspend.yaml
controllers/testdata/suspend-and-deploy.yaml
controllers/testdata/test-apply.yaml
pkg/providers/builtin/workspace.cue
pkg/providers/builtin/workspace.go
pkg/providers/builtin/workspace_test.go
pkg/providers/compiler.go

Feat: add builtin providers and fix helm

---

pkg/providers/kube/kube.go
pkg/providers/kube/kube_test.go
pkg/providers/util/util.go
pkg/providers/util/util_test.go

Fix: fix native cue providers

---

pkg/providers/http/http.cue
pkg/providers/http/http.go
pkg/providers/legacy/http/http.cue
pkg/providers/legacy/http/http.go

Fix: fix context in provider

---

pkg/executor/workflow.go
pkg/executor/workflow_test.go
pkg/providers/http/http.cue
pkg/providers/http/http.go
pkg/providers/legacy/http/http.cue
pkg/providers/legacy/http/http.go
pkg/tasks/custom/action.go

Fix: fix suspend judgement

---

README.md

Fixes #199 
I have:
open link in readme successfully
none

Docs: Readme link text bug fix

---

Dockerfile
Dockerfile.e2e
pkg/hooks/data_passing.go
pkg/hooks/data_passing_test.go

Fix: fix compatibility for output

---

.github/workflows/unit-test.yaml
pkg/context/context.go
pkg/hooks/data_passing.go
pkg/hooks/data_passing_test.go

Fixes [#6734](https://github.com/kubevela/kubevela/issues/6734)
We looked at the issue and debugged the code. We added following fixes to fix the issue:
1. Add backward compatibility for workflow outputs with builtin function.
2. We observed extra quotes coming in the string written to configmap. Replaced util.ToString to sets.ToString in writeToStore function.
I have:
We tested the code by applying KubeVela application and verified the output is proper.
```
apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
name: test-app
spec:
components: []
workflow:
steps:
- name: read-secret
type: read-object
properties:
apiVersion: v1
kind: Secret
name: mysecret
outputs:
- name: mypasswor1
valueFrom: |-
import "encoding/base64"
"\(base64.Decode(null,output.value.data["password"] ))"
``` …

Fix: Fix output

---

.github/workflows/back-port.yaml
.github/workflows/chart.yaml
.github/workflows/e2e.yaml
.github/workflows/go.yaml
.github/workflows/issue-commands.yml
.github/workflows/post-submit.yaml
.github/workflows/unit-test.yaml
.golangci.yml
Dockerfile
Dockerfile.e2e
cmd/main.go
go.mod
makefiles/dependency.mk
pkg/providers/legacy/metrics/prom_check.go
pkg/providers/metrics/prom_check.go
pkg/webhook/v1alpha1/workflowrun/validating_handler.go

Fixes #
I have:
This has been tested on a patched KubeVela setup by deploying applications and multi-cluster environments. Everything is working as expected.
- Upgraded Go version to 1.23.8.
- Upgraded golangci-lint version to 1.60.1 to align with Go 1.23.

Chore: upgrades go, golang_ci, and staticcheck version
