kubevela/workflow

pkg/cue/model/value/value_test.go, pkg/stdlib/packages.go, pkg/stdlib/packages_test.go, pkg/tasks/custom/task.go
=> Feat: optimize imports packages

controllers/workflowrun_controller.go, go.mod, go.sum, pkg/executor/workflow.go, pkg/monitor/metrics/workflow.go, pkg/monitor/watcher/workflow.go, pkg/steps/generator.go
=> Feat: add workflow metrics

.github/workflows/codeql-analysis.yaml, .github/workflows/post-submit.yaml, Dockerfile
=> Feat: add github action for image scan

pkg/executor/workflow.go, pkg/executor/workflow_test.go
=> Fix: fix the order of pending steps

.github/workflows/post-submit.yaml
=> Fix: fix github post submit actions

pkg/providers/http/do.go, pkg/providers/http/do_test.go, pkg/stdlib/pkgs/http.cue
=> Feat: add timeout in cue http provider

makefiles/const.mk
=> Fix: fix docker image name in makefile

Makefile, makefiles/const.mk
=> Fix: fix docker build makefile

.github/workflows/helm-chart.yaml, pkg/providers/http/do.go, pkg/providers/http/do_test.go, pkg/stdlib/pkgs/http.cue
=> Fix: make http parameter optional

charts/vela-workflow/templates/workflow-controller.yaml, cmd/main.go, pkg/common/logs.go
=> Feat: add flags for  writing logs to file

controllers/workflow_test.go, pkg/executor/workflow.go, pkg/tasks/custom/task.go
=> Fix: fix the workflow status when a step is failed because of rendering

pkg/providers/kube/handle.go, pkg/providers/providers.go, pkg/steps/generator.go
=> Fix: fix kube handler to make compatible

pkg/cue/utils_test.go, pkg/debug/context_test.go, pkg/providers/providers_test.go
=> Feat: add more tests

pkg/backup/interface.go, pkg/features/controller_features.go
=> Feat: add backup persister interface

.gitignore, pkg/providers/http/do.go, pkg/providers/http/do_test.go, pkg/providers/http/ratelimiter/ratelimiter.go, pkg/providers/http/ratelimiter/ratelimiter_test.go, pkg/stdlib/pkgs/http.cue
Fixes #27 
I have:
/cc @leejanee
=> Feat: add ratelimiter in http

pkg/providers/http/do_test.go
=> Fix: fix flaky test for rate limiter

controllers/workflowrun_controller.go, pkg/debug/context.go, pkg/debug/context_test.go, pkg/executor/workflow.go, pkg/executor/workflow_test.go, pkg/generator/generator.go, pkg/generator/generator_test.go, pkg/generator/suit_test.go, pkg/providers/kube/handle.go, pkg/types/types.go
=> Fix: fix CR to struct in executor

pkg/providers/http/do.go, pkg/providers/http/do_test.go, pkg/stdlib/pkgs/http.cue
=> Feat: add status code in http

.gitignore, pkg/providers/http/do.go, pkg/providers/http/do_test.go, pkg/providers/http/ratelimiter/ratelimiter.go, pkg/providers/http/ratelimiter/ratelimiter_test.go, pkg/stdlib/pkgs/http.cue
=> [Backport release-0.1] Feat: add ratelimiter in http

api/v1alpha1/event.go, api/v1alpha1/types.go, controllers/workflow_test.go, controllers/workflowrun_controller.go, go.mod, pkg/context/context.go, pkg/context/context_test.go, pkg/cue/utils_test.go, pkg/debug/context.go, pkg/debug/context_test.go, pkg/executor/interface.go, pkg/executor/workflow.go, pkg/executor/workflow_test.go, pkg/generator/generator.go, pkg/generator/generator_test.go, pkg/generator/suit_test.go, pkg/hooks/data_passing_test.go, pkg/providers/kube/handle.go, pkg/providers/kube/handle_test.go, pkg/providers/providers.go, pkg/providers/providers_test.go, pkg/steps/generator.go, pkg/tasks/custom/task_test.go, pkg/tasks/discover.go, pkg/tasks/template/load_test.go, pkg/types/types.go
=> [Backport release-0.1] Feat: add failed state in workflow

pkg/cue/model/value/value.go, pkg/cue/model/value/value_test.go
=> Fix: fix field path for cue

.golangci.yml, controllers/backup_controller.go, controllers/workflowrun_controller.go, go.mod, go.sum, pkg/cue/model/sets/utils_test.go, pkg/providers/kube/handle.go, pkg/providers/kube/handle_test.go
use three way merge patch
I have:
/cc @wangyikewxgm
=> Feat: use three way merge patch

pkg/context/context.go, pkg/context/context_test.go, pkg/utils/operation.go, pkg/utils/operation_test.go
=> Feat: add get workflow context data util func

pkg/context/context.go, pkg/cue/model/value/value.go, pkg/generator/generator.go, pkg/providers/util/util.go, pkg/providers/util/util_test.go, pkg/stdlib/pkgs/util.cue
=> Feat: add source in log provider

pkg/providers/util/util.go, pkg/types/types.go, pkg/utils/operation.go, pkg/utils/operation_test.go
add log utils for step logs
I have:
=> Feat: add log utils for step logs

pkg/providers/util/util.go, pkg/providers/util/util_test.go, pkg/stdlib/pkgs/util.cue
=> Fix: fix log level in log provider

pkg/context/context.go, pkg/context/context_test.go, pkg/executor/workflow.go, pkg/executor/workflow_test.go, pkg/utils/operation.go, pkg/utils/operation_test.go
=> Fix: fix context duplicate for differenct resources

go.mod, go.sum, pkg/cue/model/value/value.go, pkg/cue/model/value/value_test.go
Use cue fix when new value
I have:
cc @wonderflow @Somefive
=> Feat: use cue fix when new value

pkg/cue/model/sets/operation_test.go
=> Feat: add unit tests for json patch

pkg/cue/model/value/value.go
=> Fix: use fields instead of deprecated structs

.github/workflows/chart.yaml
=> Feat: add helm release github workflow

cmd/main.go, pkg/providers/kube/handle.go, pkg/providers/kube/handle_test.go, pkg/stdlib/pkgs/kube.cue
=> Feat: Delete resource by labels

pkg/mock/mock.go, pkg/providers/workspace/workspace.go, pkg/providers/workspace/workspace_test.go, pkg/stdlib/op.cue, pkg/tasks/custom/task.go, pkg/types/types.go
add op.#Message to write message in step status
I have:
=> Feat: add op.#Message to write message in step status

pkg/providers/kube/handle.go, pkg/providers/kube/handle_test.go
Fix: use add label instead of set labels
I have:
/cc @wangyikewxgm
=> Fix: use add label instead of set labels

examples/definitions/apply-deployment.cue, pkg/utils/main_test.go, pkg/utils/operation.go, pkg/utils/operation_test.go, pkg/utils/test_utils_test.go, pkg/utils/utils.go, pkg/utils/utils_test.go
=> Feat: add workflow operator for workflow run

api/v1alpha1/types.go, charts/vela-workflow/crds/core.oam.dev_workflowruns.yaml, charts/vela-workflow/crds/core.oam.dev_workflows.yaml, controllers/workflow_test.go, pkg/backup/interface_test.go, pkg/generator/generator.go
add mode in workflow template
I have:
cc @barnettZQG
=> Feat: add mode in workflow template

README.md
Signed-off-by: Jianbo Sun <jianbo.sjb@alibaba-inc.com>
Fixes #
I have:
=> Docs: add workflow usage in read me

go.mod, go.sum, pkg/executor/workflow.go, pkg/executor/workflow_test.go, pkg/stdlib/actions/v1/op.cue, pkg/stdlib/actions/v1/pkgs/email.cue, pkg/stdlib/actions/v1/pkgs/http.cue, pkg/stdlib/actions/v1/pkgs/kube.cue, pkg/stdlib/actions/v1/pkgs/ws.cue, pkg/types/types.go
=> Chore: stable the cue version and deprecate message for terminate

pkg/stdlib/actions/v1/pkgs/util.cue, pkg/stdlib/packages.go
fix filepath for windows
Ref kubevela/kubevela#4982
I have:
=> Fix: fix filepath for windows

README.md, api/v1alpha1/types.go, pkg/cue/model/sets/operation_test.go, pkg/tasks/builtin/step_group.go, pkg/tasks/builtin/step_group_test.go
Fix: small fix in docs, delete useless state and add test
I have:
=> Fix: small fix in docs, delete useless state and add test

.github/workflows/chart.yaml, Dockerfile, charts/vela-workflow/templates/workflow-controller.yaml, charts/vela-workflow/values.yaml, cmd/main.go, controllers/workflowrun_controller.go, e2e/definition_test.go, makefiles/const.mk, pkg/types/types.go
=> Feat: add controller require for canary

pkg/providers/kube/handle_test.go, pkg/stdlib/actions/v1/pkgs/kube.cue, pkg/stdlib/packages_test.go
Feat: add patch in kube.apply
Fixes: #77
I have:
=> Feat: add patch in kube.apply

README.md
=> Feat: add arch img in readme

cmd/main.go, controllers/backup_controller.go, pkg/backup/interface.go, pkg/backup/interface_test.go, pkg/backup/sls/producer.go, pkg/backup/sls/producer_test.go
=> Feat: optimiaze the sls producer instance

.github/workflows/e2e.yaml, .github/workflows/go.yaml, .github/workflows/post-submit.yaml, .github/workflows/unit-test.yaml
=> Chore: Bump version of skip duplication actions

controllers/workflow_test.go, pkg/debug/context.go, pkg/executor/workflow.go, pkg/tasks/custom/task.go
Ref kubevela/kubevela#5178
I have:
=> Fix: fix invalid debug cm name

go.mod, pkg/context/context.go, pkg/context/context_test.go, pkg/context/interface.go, pkg/executor/workflow.go, pkg/providers/kube/handle_test.go, pkg/providers/workspace/workspace.go, pkg/providers/workspace/workspace_test.go, pkg/tasks/custom/task.go, pkg/tasks/custom/task_test.go, pkg/types/types.go
=> Chore: depracate useless data in context

pkg/utils/operation.go
=> Fix: optimize restart from step func for unification

pkg/executor/workflow.go
=> Fix: clear user info in ctx when create cm for workflow context

pkg/context/context.go
=> Fix: optimize workflow context to avoid conflict error

controllers/workflow_test.go, pkg/cue/model/sets/utils.go, pkg/cue/model/value/value.go, pkg/cue/model/value/value_test.go, pkg/cue/utils.go, pkg/cue/utils_test.go, pkg/hooks/data_passing.go, pkg/hooks/data_passing_test.go, pkg/providers/kube/handle.go, pkg/tasks/custom/task_test.go
Fixes #
I have:
cc @barnettZQG
=> Feat: add set value and use it for inputs

README.md
=> Feat: add explanation in readme

README.md
=> Fix: delete table of contents

pkg/executor/workflow.go
=> Fix: omit context submission when the context is created

pkg/providers/workspace/workspace.go, pkg/providers/workspace/workspace_test.go
=> Feat: add default suspend message

.github/workflows/chart.yaml
1. remove oss for chart storage
2. add github.com/kubevela/charts upload
3. add ghcr for push image
See https://github.com/kubevela/charts/commit/21a228e4a56b8ca03ae59b5416303d48b4568392 for the auto-upload of kubevela/charts.
I have:
=> Feat: update ci for publishing

makefiles/dependency.mk, pkg/executor/workflow.go, pkg/executor/workflow_test.go, pkg/tasks/custom/task.go
=> Fix: fix suspend judgement
